# Generated by Django 4.1.7 on 2023-03-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.TextField(default=None, null=True),
        ),
    ]
