# Generated by Django 4.1.7 on 2023-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
