# Generated by Django 4.1.7 on 2023-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cor',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='apply',
            name='cov_let',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='apply',
            name='school_id',
            field=models.ImageField(upload_to=''),
        ),
    ]
