# Generated by Django 4.1.7 on 2023-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_apply_cor_alter_apply_cov_let_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cor',
            field=models.FileField(upload_to='applicant/files'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='cov_let',
            field=models.FileField(upload_to='applicant/files'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='school_id',
            field=models.ImageField(upload_to='applicant/files'),
        ),
    ]
