# Generated by Django 4.1.7 on 2023-04-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_apply_cor_alter_apply_cov_let_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='facebook',
            field=models.TextField(default=''),
        ),
    ]
