# Generated by Django 4.1.7 on 2023-04-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_apply_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=24)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apply')),
            ],
        ),
    ]
